version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystemx: gitsubmodule
    directory: /
    schedule:
      interval: weekly
