// This file was auto-generated. DO NOT EDIT!
#ifndef PEEJAY_CPRUN_HPP
#define PEEJAY_CPRUN_HPP
#include <array>
#include <cstdint>
namespace peejay {
enum class grammar_rule : std::uint8_t {
  whitespace = 0b00,
  identifier_start = 0b01,
  identifier_part = 0b11
};
constexpr auto idmask = 0b01U;
struct cprun {
  std::uint_least32_t code_point: 21;
  std::uint_least32_t length: 9;
  std::uint_least32_t rule: 2;
};
inline std::array<cprun, 586> const code_point_runs = {{
  { 0x0009, 5, 0 }, // <control> (whitespace)
  { 0x0020, 1, 0 }, // SPACE (whitespace)
  { 0x0024, 1, 1 }, // DOLLAR SIGN (identifier_start)
  { 0x0030, 10, 3 }, // DIGIT ZERO (identifier_part)
  { 0x0041, 26, 1 }, // LATIN CAPITAL LETTER A (identifier_start)
  { 0x005f, 1, 1 }, // LOW LINE (identifier_start)
  { 0x0061, 26, 1 }, // LATIN SMALL LETTER A (identifier_start)
  { 0x00a0, 1, 0 }, // NO-BREAK SPACE (whitespace)
  { 0x00b5, 1, 1 }, // MICRO SIGN (identifier_start)
  { 0x00c0, 23, 1 }, // LATIN CAPITAL LETTER A WITH GRAVE (identifier_start)
  { 0x00d8, 31, 1 }, // LATIN CAPITAL LETTER O WITH STROKE (identifier_start)
  { 0x00f8, 195, 1 }, // LATIN SMALL LETTER O WITH STROKE (identifier_start)
  { 0x01bc, 4, 1 }, // LATIN CAPITAL LETTER TONE FIVE (identifier_start)
  { 0x01c4, 208, 1 }, // LATIN CAPITAL LETTER DZ WITH CARON (identifier_start)
  { 0x0295, 45, 1 }, // LATIN LETTER PHARYNGEAL VOICED FRICATIVE (identifier_start)
  { 0x02c6, 12, 1 }, // MODIFIER LETTER CIRCUMFLEX ACCENT (identifier_start)
  { 0x02e0, 5, 1 }, // MODIFIER LETTER SMALL GAMMA (identifier_start)
  { 0x02ec, 1, 1 }, // MODIFIER LETTER VOICING (identifier_start)
  { 0x02ee, 1, 1 }, // MODIFIER LETTER DOUBLE APOSTROPHE (identifier_start)
  { 0x0300, 112, 3 }, // COMBINING GRAVE ACCENT (identifier_part)
  { 0x0370, 5, 1 }, // GREEK CAPITAL LETTER HETA (identifier_start)
  { 0x0376, 2, 1 }, // GREEK CAPITAL LETTER PAMPHYLIAN DIGAMMA (identifier_start)
  { 0x037a, 4, 1 }, // GREEK YPOGEGRAMMENI (identifier_start)
  { 0x037f, 1, 1 }, // GREEK CAPITAL LETTER YOT (identifier_start)
  { 0x0386, 1, 1 }, // GREEK CAPITAL LETTER ALPHA WITH TONOS (identifier_start)
  { 0x0388, 3, 1 }, // GREEK CAPITAL LETTER EPSILON WITH TONOS (identifier_start)
  { 0x038c, 1, 1 }, // GREEK CAPITAL LETTER OMICRON WITH TONOS (identifier_start)
  { 0x038e, 20, 1 }, // GREEK CAPITAL LETTER UPSILON WITH TONOS (identifier_start)
  { 0x03a3, 83, 1 }, // GREEK CAPITAL LETTER SIGMA (identifier_start)
  { 0x03f7, 139, 1 }, // GREEK CAPITAL LETTER SHO (identifier_start)
  { 0x0483, 5, 3 }, // COMBINING CYRILLIC TITLO (identifier_part)
  { 0x048a, 166, 1 }, // CYRILLIC CAPITAL LETTER SHORT I WITH TAIL (identifier_start)
  { 0x0531, 38, 1 }, // ARMENIAN CAPITAL LETTER AYB (identifier_start)
  { 0x0559, 1, 1 }, // ARMENIAN MODIFIER LETTER LEFT HALF RING (identifier_start)
  { 0x0560, 41, 1 }, // ARMENIAN SMALL LETTER TURNED AYB (identifier_start)
  { 0x0591, 45, 3 }, // HEBREW ACCENT ETNAHTA (identifier_part)
  { 0x05bf, 1, 3 }, // HEBREW POINT RAFE (identifier_part)
  { 0x05c1, 2, 3 }, // HEBREW POINT SHIN DOT (identifier_part)
  { 0x05c4, 2, 3 }, // HEBREW MARK UPPER DOT (identifier_part)
  { 0x05c7, 1, 3 }, // HEBREW POINT QAMATS QATAN (identifier_part)
  { 0x0610, 11, 3 }, // ARABIC SIGN SALLALLAHOU ALAYHE WASSALLAM (identifier_part)
  { 0x0640, 1, 1 }, // ARABIC TATWEEL (identifier_start)
  { 0x064b, 31, 3 }, // ARABIC FATHATAN (identifier_part)
  { 0x0670, 1, 3 }, // ARABIC LETTER SUPERSCRIPT ALEF (identifier_part)
  { 0x06d6, 7, 3 }, // ARABIC SMALL HIGH LIGATURE SAD WITH LAM WITH ALEF MAKSURA (identifier_part)
  { 0x06df, 6, 3 }, // ARABIC SMALL HIGH ROUNDED ZERO (identifier_part)
  { 0x06e5, 2, 1 }, // ARABIC SMALL WAW (identifier_start)
  { 0x06e7, 2, 3 }, // ARABIC SMALL HIGH YEH (identifier_part)
  { 0x06ea, 4, 3 }, // ARABIC EMPTY CENTRE LOW STOP (identifier_part)
  { 0x06f0, 10, 3 }, // EXTENDED ARABIC-INDIC DIGIT ZERO (identifier_part)
  { 0x0711, 1, 3 }, // SYRIAC LETTER SUPERSCRIPT ALAPH (identifier_part)
  { 0x0730, 27, 3 }, // SYRIAC PTHAHA ABOVE (identifier_part)
  { 0x07a6, 11, 3 }, // THAANA ABAFILI (identifier_part)
  { 0x07c0, 10, 3 }, // NKO DIGIT ZERO (identifier_part)
  { 0x07eb, 9, 3 }, // NKO COMBINING SHORT HIGH TONE (identifier_part)
  { 0x07f4, 2, 1 }, // NKO HIGH TONE APOSTROPHE (identifier_start)
  { 0x07fa, 1, 1 }, // NKO LAJANYALAN (identifier_start)
  { 0x07fd, 1, 3 }, // NKO DANTAYALAN (identifier_part)
  { 0x0816, 4, 3 }, // SAMARITAN MARK IN (identifier_part)
  { 0x081a, 1, 1 }, // SAMARITAN MODIFIER LETTER EPENTHETIC YUT (identifier_start)
  { 0x081b, 9, 3 }, // SAMARITAN MARK EPENTHETIC YUT (identifier_part)
  { 0x0824, 1, 1 }, // SAMARITAN MODIFIER LETTER SHORT A (identifier_start)
  { 0x0825, 3, 3 }, // SAMARITAN VOWEL SIGN SHORT A (identifier_part)
  { 0x0828, 1, 1 }, // SAMARITAN MODIFIER LETTER I (identifier_start)
  { 0x0829, 5, 3 }, // SAMARITAN VOWEL SIGN LONG I (identifier_part)
  { 0x0859, 3, 3 }, // MANDAIC AFFRICATION MARK (identifier_part)
  { 0x0898, 8, 3 }, // ARABIC SMALL HIGH WORD AL-JUZ (identifier_part)
  { 0x08c9, 1, 1 }, // ARABIC SMALL FARSI YEH (identifier_start)
  { 0x08ca, 24, 3 }, // ARABIC SMALL HIGH FARSI YEH (identifier_part)
  { 0x08e3, 33, 3 }, // ARABIC TURNED DAMMA BELOW (identifier_part)
  { 0x093a, 3, 3 }, // DEVANAGARI VOWEL SIGN OE (identifier_part)
  { 0x093e, 18, 3 }, // DEVANAGARI VOWEL SIGN AA (identifier_part)
  { 0x0951, 7, 3 }, // DEVANAGARI STRESS SIGN UDATTA (identifier_part)
  { 0x0962, 2, 3 }, // DEVANAGARI VOWEL SIGN VOCALIC L (identifier_part)
  { 0x0966, 10, 3 }, // DEVANAGARI DIGIT ZERO (identifier_part)
  { 0x0971, 1, 1 }, // DEVANAGARI SIGN HIGH SPACING DOT (identifier_start)
  { 0x0981, 3, 3 }, // BENGALI SIGN CANDRABINDU (identifier_part)
  { 0x09bc, 1, 3 }, // BENGALI SIGN NUKTA (identifier_part)
  { 0x09be, 7, 3 }, // BENGALI VOWEL SIGN AA (identifier_part)
  { 0x09c7, 2, 3 }, // BENGALI VOWEL SIGN E (identifier_part)
  { 0x09cb, 3, 3 }, // BENGALI VOWEL SIGN O (identifier_part)
  { 0x09d7, 1, 3 }, // BENGALI AU LENGTH MARK (identifier_part)
  { 0x09e2, 2, 3 }, // BENGALI VOWEL SIGN VOCALIC L (identifier_part)
  { 0x09e6, 10, 3 }, // BENGALI DIGIT ZERO (identifier_part)
  { 0x09fe, 1, 3 }, // BENGALI SANDHI MARK (identifier_part)
  { 0x0a01, 3, 3 }, // GURMUKHI SIGN ADAK BINDI (identifier_part)
  { 0x0a3c, 1, 3 }, // GURMUKHI SIGN NUKTA (identifier_part)
  { 0x0a3e, 5, 3 }, // GURMUKHI VOWEL SIGN AA (identifier_part)
  { 0x0a47, 2, 3 }, // GURMUKHI VOWEL SIGN EE (identifier_part)
  { 0x0a4b, 3, 3 }, // GURMUKHI VOWEL SIGN OO (identifier_part)
  { 0x0a51, 1, 3 }, // GURMUKHI SIGN UDAAT (identifier_part)
  { 0x0a66, 12, 3 }, // GURMUKHI DIGIT ZERO (identifier_part)
  { 0x0a75, 1, 3 }, // GURMUKHI SIGN YAKASH (identifier_part)
  { 0x0a81, 3, 3 }, // GUJARATI SIGN CANDRABINDU (identifier_part)
  { 0x0abc, 1, 3 }, // GUJARATI SIGN NUKTA (identifier_part)
  { 0x0abe, 8, 3 }, // GUJARATI VOWEL SIGN AA (identifier_part)
  { 0x0ac7, 3, 3 }, // GUJARATI VOWEL SIGN E (identifier_part)
  { 0x0acb, 3, 3 }, // GUJARATI VOWEL SIGN O (identifier_part)
  { 0x0ae2, 2, 3 }, // GUJARATI VOWEL SIGN VOCALIC L (identifier_part)
  { 0x0ae6, 10, 3 }, // GUJARATI DIGIT ZERO (identifier_part)
  { 0x0afa, 6, 3 }, // GUJARATI SIGN SUKUN (identifier_part)
  { 0x0b01, 3, 3 }, // ORIYA SIGN CANDRABINDU (identifier_part)
  { 0x0b3c, 1, 3 }, // ORIYA SIGN NUKTA (identifier_part)
  { 0x0b3e, 7, 3 }, // ORIYA VOWEL SIGN AA (identifier_part)
  { 0x0b47, 2, 3 }, // ORIYA VOWEL SIGN E (identifier_part)
  { 0x0b4b, 3, 3 }, // ORIYA VOWEL SIGN O (identifier_part)
  { 0x0b55, 3, 3 }, // ORIYA SIGN OVERLINE (identifier_part)
  { 0x0b62, 2, 3 }, // ORIYA VOWEL SIGN VOCALIC L (identifier_part)
  { 0x0b66, 10, 3 }, // ORIYA DIGIT ZERO (identifier_part)
  { 0x0b82, 1, 3 }, // TAMIL SIGN ANUSVARA (identifier_part)
  { 0x0bbe, 5, 3 }, // TAMIL VOWEL SIGN AA (identifier_part)
  { 0x0bc6, 3, 3 }, // TAMIL VOWEL SIGN E (identifier_part)
  { 0x0bca, 4, 3 }, // TAMIL VOWEL SIGN O (identifier_part)
  { 0x0bd7, 1, 3 }, // TAMIL AU LENGTH MARK (identifier_part)
  { 0x0be6, 10, 3 }, // TAMIL DIGIT ZERO (identifier_part)
  { 0x0c00, 5, 3 }, // TELUGU SIGN COMBINING CANDRABINDU ABOVE (identifier_part)
  { 0x0c3c, 1, 3 }, // TELUGU SIGN NUKTA (identifier_part)
  { 0x0c3e, 7, 3 }, // TELUGU VOWEL SIGN AA (identifier_part)
  { 0x0c46, 3, 3 }, // TELUGU VOWEL SIGN E (identifier_part)
  { 0x0c4a, 4, 3 }, // TELUGU VOWEL SIGN O (identifier_part)
  { 0x0c55, 2, 3 }, // TELUGU LENGTH MARK (identifier_part)
  { 0x0c62, 2, 3 }, // TELUGU VOWEL SIGN VOCALIC L (identifier_part)
  { 0x0c66, 10, 3 }, // TELUGU DIGIT ZERO (identifier_part)
  { 0x0c81, 3, 3 }, // KANNADA SIGN CANDRABINDU (identifier_part)
  { 0x0cbc, 1, 3 }, // KANNADA SIGN NUKTA (identifier_part)
  { 0x0cbe, 7, 3 }, // KANNADA VOWEL SIGN AA (identifier_part)
  { 0x0cc6, 3, 3 }, // KANNADA VOWEL SIGN E (identifier_part)
  { 0x0cca, 4, 3 }, // KANNADA VOWEL SIGN O (identifier_part)
  { 0x0cd5, 2, 3 }, // KANNADA LENGTH MARK (identifier_part)
  { 0x0ce2, 2, 3 }, // KANNADA VOWEL SIGN VOCALIC L (identifier_part)
  { 0x0ce6, 10, 3 }, // KANNADA DIGIT ZERO (identifier_part)
  { 0x0cf3, 1, 3 }, // KANNADA SIGN COMBINING ANUSVARA ABOVE RIGHT (identifier_part)
  { 0x0d00, 4, 3 }, // MALAYALAM SIGN COMBINING ANUSVARA ABOVE (identifier_part)
  { 0x0d3b, 2, 3 }, // MALAYALAM SIGN VERTICAL BAR VIRAMA (identifier_part)
  { 0x0d3e, 7, 3 }, // MALAYALAM VOWEL SIGN AA (identifier_part)
  { 0x0d46, 3, 3 }, // MALAYALAM VOWEL SIGN E (identifier_part)
  { 0x0d4a, 4, 3 }, // MALAYALAM VOWEL SIGN O (identifier_part)
  { 0x0d57, 1, 3 }, // MALAYALAM AU LENGTH MARK (identifier_part)
  { 0x0d62, 2, 3 }, // MALAYALAM VOWEL SIGN VOCALIC L (identifier_part)
  { 0x0d66, 10, 3 }, // MALAYALAM DIGIT ZERO (identifier_part)
  { 0x0d81, 3, 3 }, // SINHALA SIGN CANDRABINDU (identifier_part)
  { 0x0dca, 1, 3 }, // SINHALA SIGN AL-LAKUNA (identifier_part)
  { 0x0dcf, 6, 3 }, // SINHALA VOWEL SIGN AELA-PILLA (identifier_part)
  { 0x0dd6, 1, 3 }, // SINHALA VOWEL SIGN DIGA PAA-PILLA (identifier_part)
  { 0x0dd8, 8, 3 }, // SINHALA VOWEL SIGN GAETTA-PILLA (identifier_part)
  { 0x0de6, 10, 3 }, // SINHALA LITH DIGIT ZERO (identifier_part)
  { 0x0df2, 2, 3 }, // SINHALA VOWEL SIGN DIGA GAETTA-PILLA (identifier_part)
  { 0x0e31, 1, 3 }, // THAI CHARACTER MAI HAN-AKAT (identifier_part)
  { 0x0e34, 7, 3 }, // THAI CHARACTER SARA I (identifier_part)
  { 0x0e46, 1, 1 }, // THAI CHARACTER MAIYAMOK (identifier_start)
  { 0x0e47, 8, 3 }, // THAI CHARACTER MAITAIKHU (identifier_part)
  { 0x0e50, 10, 3 }, // THAI DIGIT ZERO (identifier_part)
  { 0x0eb1, 1, 3 }, // LAO VOWEL SIGN MAI KAN (identifier_part)
  { 0x0eb4, 9, 3 }, // LAO VOWEL SIGN I (identifier_part)
  { 0x0ec6, 1, 1 }, // LAO KO LA (identifier_start)
  { 0x0ec8, 7, 3 }, // LAO TONE MAI EK (identifier_part)
  { 0x0ed0, 10, 3 }, // LAO DIGIT ZERO (identifier_part)
  { 0x0f18, 2, 3 }, // TIBETAN ASTROLOGICAL SIGN -KHYUD PA (identifier_part)
  { 0x0f20, 10, 3 }, // TIBETAN DIGIT ZERO (identifier_part)
  { 0x0f35, 1, 3 }, // TIBETAN MARK NGAS BZUNG NYI ZLA (identifier_part)
  { 0x0f37, 1, 3 }, // TIBETAN MARK NGAS BZUNG SGOR RTAGS (identifier_part)
  { 0x0f39, 1, 3 }, // TIBETAN MARK TSA -PHRU (identifier_part)
  { 0x0f3e, 2, 3 }, // TIBETAN SIGN YAR TSHES (identifier_part)
  { 0x0f71, 20, 3 }, // TIBETAN VOWEL SIGN AA (identifier_part)
  { 0x0f86, 2, 3 }, // TIBETAN SIGN LCI RTAGS (identifier_part)
  { 0x0f8d, 11, 3 }, // TIBETAN SUBJOINED SIGN LCE TSA CAN (identifier_part)
  { 0x0f99, 36, 3 }, // TIBETAN SUBJOINED LETTER NYA (identifier_part)
  { 0x0fc6, 1, 3 }, // TIBETAN SYMBOL PADMA GDAN (identifier_part)
  { 0x102b, 20, 3 }, // MYANMAR VOWEL SIGN TALL AA (identifier_part)
  { 0x1040, 10, 3 }, // MYANMAR DIGIT ZERO (identifier_part)
  { 0x1056, 4, 3 }, // MYANMAR VOWEL SIGN VOCALIC R (identifier_part)
  { 0x105e, 3, 3 }, // MYANMAR CONSONANT SIGN MON MEDIAL NA (identifier_part)
  { 0x1062, 3, 3 }, // MYANMAR VOWEL SIGN SGAW KAREN EU (identifier_part)
  { 0x1067, 7, 3 }, // MYANMAR VOWEL SIGN WESTERN PWO KAREN EU (identifier_part)
  { 0x1071, 4, 3 }, // MYANMAR VOWEL SIGN GEBA KAREN I (identifier_part)
  { 0x1082, 12, 3 }, // MYANMAR CONSONANT SIGN SHAN MEDIAL WA (identifier_part)
  { 0x108f, 15, 3 }, // MYANMAR SIGN RUMAI PALAUNG TONE-5 (identifier_part)
  { 0x10a0, 38, 1 }, // GEORGIAN CAPITAL LETTER AN (identifier_start)
  { 0x10c7, 1, 1 }, // GEORGIAN CAPITAL LETTER YN (identifier_start)
  { 0x10cd, 1, 1 }, // GEORGIAN CAPITAL LETTER AEN (identifier_start)
  { 0x10d0, 43, 1 }, // GEORGIAN LETTER AN (identifier_start)
  { 0x10fc, 4, 1 }, // MODIFIER LETTER GEORGIAN NAR (identifier_start)
  { 0x135d, 3, 3 }, // ETHIOPIC COMBINING GEMINATION AND VOWEL LENGTH MARK (identifier_part)
  { 0x13a0, 86, 1 }, // CHEROKEE LETTER A (identifier_start)
  { 0x13f8, 6, 1 }, // CHEROKEE SMALL LETTER YE (identifier_start)
  { 0x1680, 1, 0 }, // OGHAM SPACE MARK (whitespace)
  { 0x16ee, 3, 1 }, // RUNIC ARLAUG SYMBOL (identifier_start)
  { 0x1712, 4, 3 }, // TAGALOG VOWEL SIGN I (identifier_part)
  { 0x1732, 3, 3 }, // HANUNOO VOWEL SIGN I (identifier_part)
  { 0x1752, 2, 3 }, // BUHID VOWEL SIGN I (identifier_part)
  { 0x1772, 2, 3 }, // TAGBANWA VOWEL SIGN I (identifier_part)
  { 0x17b4, 32, 3 }, // KHMER VOWEL INHERENT AQ (identifier_part)
  { 0x17d7, 1, 1 }, // KHMER SIGN LEK TOO (identifier_start)
  { 0x17dd, 1, 3 }, // KHMER SIGN ATTHACAN (identifier_part)
  { 0x17e0, 10, 3 }, // KHMER DIGIT ZERO (identifier_part)
  { 0x180b, 3, 3 }, // MONGOLIAN FREE VARIATION SELECTOR ONE (identifier_part)
  { 0x180f, 11, 3 }, // MONGOLIAN FREE VARIATION SELECTOR FOUR (identifier_part)
  { 0x1843, 1, 1 }, // MONGOLIAN LETTER TODO LONG VOWEL SIGN (identifier_start)
  { 0x1885, 2, 3 }, // MONGOLIAN LETTER ALI GALI BALUDA (identifier_part)
  { 0x18a9, 1, 3 }, // MONGOLIAN LETTER ALI GALI DAGALGA (identifier_part)
  { 0x1920, 12, 3 }, // LIMBU VOWEL SIGN A (identifier_part)
  { 0x1930, 12, 3 }, // LIMBU SMALL LETTER KA (identifier_part)
  { 0x1946, 10, 3 }, // LIMBU DIGIT ZERO (identifier_part)
  { 0x19d0, 10, 3 }, // NEW TAI LUE DIGIT ZERO (identifier_part)
  { 0x1a17, 5, 3 }, // BUGINESE VOWEL SIGN I (identifier_part)
  { 0x1a55, 10, 3 }, // TAI THAM CONSONANT SIGN MEDIAL RA (identifier_part)
  { 0x1a60, 29, 3 }, // TAI THAM SIGN SAKOT (identifier_part)
  { 0x1a7f, 11, 3 }, // TAI THAM COMBINING CRYPTOGRAMMIC DOT (identifier_part)
  { 0x1a90, 10, 3 }, // TAI THAM THAM DIGIT ZERO (identifier_part)
  { 0x1aa7, 1, 1 }, // TAI THAM SIGN MAI YAMOK (identifier_start)
  { 0x1ab0, 14, 3 }, // COMBINING DOUBLED CIRCUMFLEX ACCENT (identifier_part)
  { 0x1abf, 16, 3 }, // COMBINING LATIN SMALL LETTER W BELOW (identifier_part)
  { 0x1b00, 5, 3 }, // BALINESE SIGN ULU RICEM (identifier_part)
  { 0x1b34, 17, 3 }, // BALINESE SIGN REREKAN (identifier_part)
  { 0x1b50, 10, 3 }, // BALINESE DIGIT ZERO (identifier_part)
  { 0x1b6b, 9, 3 }, // BALINESE MUSICAL SYMBOL COMBINING TEGEH (identifier_part)
  { 0x1b80, 3, 3 }, // SUNDANESE SIGN PANYECEK (identifier_part)
  { 0x1ba1, 13, 3 }, // SUNDANESE CONSONANT SIGN PAMINGKAL (identifier_part)
  { 0x1bb0, 10, 3 }, // SUNDANESE DIGIT ZERO (identifier_part)
  { 0x1be6, 14, 3 }, // BATAK SIGN TOMPI (identifier_part)
  { 0x1c24, 20, 3 }, // LEPCHA SUBJOINED LETTER YA (identifier_part)
  { 0x1c40, 10, 3 }, // LEPCHA DIGIT ZERO (identifier_part)
  { 0x1c50, 10, 3 }, // OL CHIKI DIGIT ZERO (identifier_part)
  { 0x1c78, 6, 1 }, // OL CHIKI MU TTUDDAG (identifier_start)
  { 0x1c80, 9, 1 }, // CYRILLIC SMALL LETTER ROUNDED VE (identifier_start)
  { 0x1c90, 43, 1 }, // GEORGIAN MTAVRULI CAPITAL LETTER AN (identifier_start)
  { 0x1cbd, 3, 1 }, // GEORGIAN MTAVRULI CAPITAL LETTER AEN (identifier_start)
  { 0x1cd0, 3, 3 }, // VEDIC TONE KARSHANA (identifier_part)
  { 0x1cd4, 21, 3 }, // VEDIC SIGN YAJURVEDIC MIDLINE SVARITA (identifier_part)
  { 0x1ced, 1, 3 }, // VEDIC SIGN TIRYAK (identifier_part)
  { 0x1cf4, 1, 3 }, // VEDIC TONE CANDRA ABOVE (identifier_part)
  { 0x1cf7, 3, 3 }, // VEDIC SIGN ATIKRAMA (identifier_part)
  { 0x1d00, 192, 1 }, // LATIN LETTER SMALL CAPITAL A (identifier_start)
  { 0x1dc0, 64, 3 }, // COMBINING DOTTED GRAVE ACCENT (identifier_part)
  { 0x1e00, 278, 1 }, // LATIN CAPITAL LETTER A WITH RING BELOW (identifier_start)
  { 0x1f18, 6, 1 }, // GREEK CAPITAL LETTER EPSILON WITH PSILI (identifier_start)
  { 0x1f20, 38, 1 }, // GREEK SMALL LETTER ETA WITH PSILI (identifier_start)
  { 0x1f48, 6, 1 }, // GREEK CAPITAL LETTER OMICRON WITH PSILI (identifier_start)
  { 0x1f50, 8, 1 }, // GREEK SMALL LETTER UPSILON WITH PSILI (identifier_start)
  { 0x1f59, 1, 1 }, // GREEK CAPITAL LETTER UPSILON WITH DASIA (identifier_start)
  { 0x1f5b, 1, 1 }, // GREEK CAPITAL LETTER UPSILON WITH DASIA AND VARIA (identifier_start)
  { 0x1f5d, 1, 1 }, // GREEK CAPITAL LETTER UPSILON WITH DASIA AND OXIA (identifier_start)
  { 0x1f5f, 31, 1 }, // GREEK CAPITAL LETTER UPSILON WITH DASIA AND PERISPOMENI (identifier_start)
  { 0x1f80, 53, 1 }, // GREEK SMALL LETTER ALPHA WITH PSILI AND YPOGEGRAMMENI (identifier_start)
  { 0x1fb6, 7, 1 }, // GREEK SMALL LETTER ALPHA WITH PERISPOMENI (identifier_start)
  { 0x1fbe, 1, 1 }, // GREEK PROSGEGRAMMENI (identifier_start)
  { 0x1fc2, 3, 1 }, // GREEK SMALL LETTER ETA WITH VARIA AND YPOGEGRAMMENI (identifier_start)
  { 0x1fc6, 7, 1 }, // GREEK SMALL LETTER ETA WITH PERISPOMENI (identifier_start)
  { 0x1fd0, 4, 1 }, // GREEK SMALL LETTER IOTA WITH VRACHY (identifier_start)
  { 0x1fd6, 6, 1 }, // GREEK SMALL LETTER IOTA WITH PERISPOMENI (identifier_start)
  { 0x1fe0, 13, 1 }, // GREEK SMALL LETTER UPSILON WITH VRACHY (identifier_start)
  { 0x1ff2, 3, 1 }, // GREEK SMALL LETTER OMEGA WITH VARIA AND YPOGEGRAMMENI (identifier_start)
  { 0x1ff6, 7, 1 }, // GREEK SMALL LETTER OMEGA WITH PERISPOMENI (identifier_start)
  { 0x2000, 11, 0 }, // EN QUAD (whitespace)
  { 0x200c, 2, 3 }, // ZERO WIDTH NON-JOINER (identifier_part)
  { 0x202f, 1, 0 }, // NARROW NO-BREAK SPACE (whitespace)
  { 0x203f, 2, 3 }, // UNDERTIE (identifier_part)
  { 0x2054, 1, 3 }, // INVERTED UNDERTIE (identifier_part)
  { 0x205f, 1, 0 }, // MEDIUM MATHEMATICAL SPACE (whitespace)
  { 0x2071, 1, 1 }, // SUPERSCRIPT LATIN SMALL LETTER I (identifier_start)
  { 0x207f, 1, 1 }, // SUPERSCRIPT LATIN SMALL LETTER N (identifier_start)
  { 0x2090, 13, 1 }, // LATIN SUBSCRIPT SMALL LETTER A (identifier_start)
  { 0x20d0, 13, 3 }, // COMBINING LEFT HARPOON ABOVE (identifier_part)
  { 0x20e1, 1, 3 }, // COMBINING LEFT RIGHT ARROW ABOVE (identifier_part)
  { 0x20e5, 12, 3 }, // COMBINING REVERSE SOLIDUS OVERLAY (identifier_part)
  { 0x2102, 1, 1 }, // DOUBLE-STRUCK CAPITAL C (identifier_start)
  { 0x2107, 1, 1 }, // EULER CONSTANT (identifier_start)
  { 0x210a, 10, 1 }, // SCRIPT SMALL G (identifier_start)
  { 0x2115, 1, 1 }, // DOUBLE-STRUCK CAPITAL N (identifier_start)
  { 0x2119, 5, 1 }, // DOUBLE-STRUCK CAPITAL P (identifier_start)
  { 0x2124, 1, 1 }, // DOUBLE-STRUCK CAPITAL Z (identifier_start)
  { 0x2126, 1, 1 }, // OHM SIGN (identifier_start)
  { 0x2128, 1, 1 }, // BLACK-LETTER CAPITAL Z (identifier_start)
  { 0x212a, 4, 1 }, // KELVIN SIGN (identifier_start)
  { 0x212f, 6, 1 }, // SCRIPT SMALL E (identifier_start)
  { 0x2139, 1, 1 }, // INFORMATION SOURCE (identifier_start)
  { 0x213c, 4, 1 }, // DOUBLE-STRUCK SMALL PI (identifier_start)
  { 0x2145, 5, 1 }, // DOUBLE-STRUCK ITALIC CAPITAL D (identifier_start)
  { 0x214e, 1, 1 }, // TURNED SMALL F (identifier_start)
  { 0x2160, 41, 1 }, // ROMAN NUMERAL ONE (identifier_start)
  { 0x2c00, 229, 1 }, // GLAGOLITIC CAPITAL LETTER AZU (identifier_start)
  { 0x2ceb, 4, 1 }, // COPTIC CAPITAL LETTER CRYPTOGRAMMIC SHEI (identifier_start)
  { 0x2cef, 3, 3 }, // COPTIC COMBINING NI ABOVE (identifier_part)
  { 0x2cf2, 2, 1 }, // COPTIC CAPITAL LETTER BOHAIRIC KHEI (identifier_start)
  { 0x2d00, 38, 1 }, // GEORGIAN SMALL LETTER AN (identifier_start)
  { 0x2d27, 1, 1 }, // GEORGIAN SMALL LETTER YN (identifier_start)
  { 0x2d2d, 1, 1 }, // GEORGIAN SMALL LETTER AEN (identifier_start)
  { 0x2d6f, 1, 1 }, // TIFINAGH MODIFIER LETTER LABIALIZATION MARK (identifier_start)
  { 0x2d7f, 1, 3 }, // TIFINAGH CONSONANT JOINER (identifier_part)
  { 0x2de0, 32, 3 }, // COMBINING CYRILLIC LETTER BE (identifier_part)
  { 0x2e2f, 1, 1 }, // VERTICAL TILDE (identifier_start)
  { 0x3000, 1, 0 }, // IDEOGRAPHIC SPACE (whitespace)
  { 0x3005, 1, 1 }, // IDEOGRAPHIC ITERATION MARK (identifier_start)
  { 0x3007, 1, 1 }, // IDEOGRAPHIC NUMBER ZERO (identifier_start)
  { 0x3021, 9, 1 }, // HANGZHOU NUMERAL ONE (identifier_start)
  { 0x302a, 6, 3 }, // IDEOGRAPHIC LEVEL TONE MARK (identifier_part)
  { 0x3031, 5, 1 }, // VERTICAL KANA REPEAT MARK (identifier_start)
  { 0x3038, 4, 1 }, // HANGZHOU NUMERAL TEN (identifier_start)
  { 0x3099, 2, 3 }, // COMBINING KATAKANA-HIRAGANA VOICED SOUND MARK (identifier_part)
  { 0x309d, 2, 1 }, // HIRAGANA ITERATION MARK (identifier_start)
  { 0x30fc, 3, 1 }, // KATAKANA-HIRAGANA PROLONGED SOUND MARK (identifier_start)
  { 0xa015, 1, 1 }, // YI SYLLABLE WU (identifier_start)
  { 0xa4f8, 6, 1 }, // LISU LETTER TONE MYA TI (identifier_start)
  { 0xa60c, 1, 1 }, // VAI SYLLABLE LENGTHENER (identifier_start)
  { 0xa620, 10, 3 }, // VAI DIGIT ZERO (identifier_part)
  { 0xa640, 46, 1 }, // CYRILLIC CAPITAL LETTER ZEMLYA (identifier_start)
  { 0xa66f, 1, 3 }, // COMBINING CYRILLIC VZMET (identifier_part)
  { 0xa674, 10, 3 }, // COMBINING CYRILLIC LETTER UKRAINIAN IE (identifier_part)
  { 0xa67f, 31, 1 }, // CYRILLIC PAYEROK (identifier_start)
  { 0xa69e, 2, 3 }, // COMBINING CYRILLIC LETTER EF (identifier_part)
  { 0xa6e6, 10, 1 }, // BAMUM LETTER MO (identifier_start)
  { 0xa6f0, 2, 3 }, // BAMUM COMBINING MARK KOQNDON (identifier_part)
  { 0xa717, 9, 1 }, // MODIFIER LETTER DOT VERTICAL BAR (identifier_start)
  { 0xa722, 103, 1 }, // LATIN CAPITAL LETTER EGYPTOLOGICAL ALEF (identifier_start)
  { 0xa78b, 4, 1 }, // LATIN CAPITAL LETTER SALTILLO (identifier_start)
  { 0xa790, 59, 1 }, // LATIN CAPITAL LETTER N WITH DESCENDER (identifier_start)
  { 0xa7d0, 2, 1 }, // LATIN CAPITAL LETTER CLOSED INSULAR G (identifier_start)
  { 0xa7d3, 1, 1 }, // LATIN SMALL LETTER DOUBLE THORN (identifier_start)
  { 0xa7d5, 5, 1 }, // LATIN SMALL LETTER DOUBLE WYNN (identifier_start)
  { 0xa7f2, 5, 1 }, // MODIFIER LETTER CAPITAL C (identifier_start)
  { 0xa7f8, 3, 1 }, // MODIFIER LETTER CAPITAL H WITH STROKE (identifier_start)
  { 0xa802, 1, 3 }, // SYLOTI NAGRI SIGN DVISVARA (identifier_part)
  { 0xa806, 1, 3 }, // SYLOTI NAGRI SIGN HASANTA (identifier_part)
  { 0xa80b, 1, 3 }, // SYLOTI NAGRI SIGN ANUSVARA (identifier_part)
  { 0xa823, 5, 3 }, // SYLOTI NAGRI VOWEL SIGN A (identifier_part)
  { 0xa82c, 1, 3 }, // SYLOTI NAGRI SIGN ALTERNATE HASANTA (identifier_part)
  { 0xa880, 2, 3 }, // SAURASHTRA SIGN ANUSVARA (identifier_part)
  { 0xa8b4, 18, 3 }, // SAURASHTRA CONSONANT SIGN HAARU (identifier_part)
  { 0xa8d0, 10, 3 }, // SAURASHTRA DIGIT ZERO (identifier_part)
  { 0xa8e0, 18, 3 }, // COMBINING DEVANAGARI DIGIT ZERO (identifier_part)
  { 0xa8ff, 11, 3 }, // DEVANAGARI VOWEL SIGN AY (identifier_part)
  { 0xa926, 8, 3 }, // KAYAH LI VOWEL UE (identifier_part)
  { 0xa947, 13, 3 }, // REJANG VOWEL SIGN I (identifier_part)
  { 0xa980, 4, 3 }, // JAVANESE SIGN PANYANGGA (identifier_part)
  { 0xa9b3, 14, 3 }, // JAVANESE SIGN CECAK TELU (identifier_part)
  { 0xa9cf, 1, 1 }, // JAVANESE PANGRANGKEP (identifier_start)
  { 0xa9d0, 10, 3 }, // JAVANESE DIGIT ZERO (identifier_part)
  { 0xa9e5, 1, 3 }, // MYANMAR SIGN SHAN SAW (identifier_part)
  { 0xa9e6, 1, 1 }, // MYANMAR MODIFIER LETTER SHAN REDUPLICATION (identifier_start)
  { 0xa9f0, 10, 3 }, // MYANMAR TAI LAING DIGIT ZERO (identifier_part)
  { 0xaa29, 14, 3 }, // CHAM VOWEL SIGN AA (identifier_part)
  { 0xaa43, 1, 3 }, // CHAM CONSONANT SIGN FINAL NG (identifier_part)
  { 0xaa4c, 2, 3 }, // CHAM CONSONANT SIGN FINAL M (identifier_part)
  { 0xaa50, 10, 3 }, // CHAM DIGIT ZERO (identifier_part)
  { 0xaa70, 1, 1 }, // MYANMAR MODIFIER LETTER KHAMTI REDUPLICATION (identifier_start)
  { 0xaa7b, 3, 3 }, // MYANMAR SIGN PAO KAREN TONE (identifier_part)
  { 0xaab0, 1, 3 }, // TAI VIET MAI KANG (identifier_part)
  { 0xaab2, 3, 3 }, // TAI VIET VOWEL I (identifier_part)
  { 0xaab7, 2, 3 }, // TAI VIET MAI KHIT (identifier_part)
  { 0xaabe, 2, 3 }, // TAI VIET VOWEL AM (identifier_part)
  { 0xaac1, 1, 3 }, // TAI VIET TONE MAI THO (identifier_part)
  { 0xaadd, 1, 1 }, // TAI VIET SYMBOL SAM (identifier_start)
  { 0xaaeb, 5, 3 }, // MEETEI MAYEK VOWEL SIGN II (identifier_part)
  { 0xaaf3, 2, 1 }, // MEETEI MAYEK SYLLABLE REPETITION MARK (identifier_start)
  { 0xaaf5, 2, 3 }, // MEETEI MAYEK VOWEL SIGN VISARGA (identifier_part)
  { 0xab30, 43, 1 }, // LATIN SMALL LETTER BARRED ALPHA (identifier_start)
  { 0xab5c, 14, 1 }, // MODIFIER LETTER SMALL HENG (identifier_start)
  { 0xab70, 80, 1 }, // CHEROKEE SMALL LETTER A (identifier_start)
  { 0xabe3, 8, 3 }, // MEETEI MAYEK VOWEL SIGN ONAP (identifier_part)
  { 0xabec, 2, 3 }, // MEETEI MAYEK LUM IYEK (identifier_part)
  { 0xabf0, 10, 3 }, // MEETEI MAYEK DIGIT ZERO (identifier_part)
  { 0xfb00, 7, 1 }, // LATIN SMALL LIGATURE FF (identifier_start)
  { 0xfb13, 5, 1 }, // ARMENIAN SMALL LIGATURE MEN NOW (identifier_start)
  { 0xfb1e, 1, 3 }, // HEBREW POINT JUDEO-SPANISH VARIKA (identifier_part)
  { 0xfe00, 16, 3 }, // VARIATION SELECTOR-1 (identifier_part)
  { 0xfe20, 16, 3 }, // COMBINING LIGATURE LEFT HALF (identifier_part)
  { 0xfe33, 2, 3 }, // PRESENTATION FORM FOR VERTICAL LOW LINE (identifier_part)
  { 0xfe4d, 3, 3 }, // DASHED LOW LINE (identifier_part)
  { 0xfeff, 1, 0 }, // ZERO WIDTH NO-BREAK SPACE (whitespace)
  { 0xff10, 10, 3 }, // FULLWIDTH DIGIT ZERO (identifier_part)
  { 0xff21, 26, 1 }, // FULLWIDTH LATIN CAPITAL LETTER A (identifier_start)
  { 0xff3f, 1, 3 }, // FULLWIDTH LOW LINE (identifier_part)
  { 0xff41, 26, 1 }, // FULLWIDTH LATIN SMALL LETTER A (identifier_start)
  { 0xff70, 1, 1 }, // HALFWIDTH KATAKANA-HIRAGANA PROLONGED SOUND MARK (identifier_start)
  { 0xff9e, 2, 1 }, // HALFWIDTH KATAKANA VOICED SOUND MARK (identifier_start)
  { 0x10140, 53, 1 }, // GREEK ACROPHONIC ATTIC ONE QUARTER (identifier_start)
  { 0x101fd, 1, 3 }, // PHAISTOS DISC SIGN COMBINING OBLIQUE STROKE (identifier_part)
  { 0x102e0, 1, 3 }, // COPTIC EPACT THOUSANDS MARK (identifier_part)
  { 0x10341, 1, 1 }, // GOTHIC LETTER NINETY (identifier_start)
  { 0x1034a, 1, 1 }, // GOTHIC LETTER NINE HUNDRED (identifier_start)
  { 0x10376, 5, 3 }, // COMBINING OLD PERMIC LETTER AN (identifier_part)
  { 0x103d1, 5, 1 }, // OLD PERSIAN NUMBER ONE (identifier_start)
  { 0x10400, 80, 1 }, // DESERET CAPITAL LETTER LONG I (identifier_start)
  { 0x104a0, 10, 3 }, // OSMANYA DIGIT ZERO (identifier_part)
  { 0x104b0, 36, 1 }, // OSAGE CAPITAL LETTER A (identifier_start)
  { 0x104d8, 36, 1 }, // OSAGE SMALL LETTER A (identifier_start)
  { 0x10570, 11, 1 }, // VITHKUQI CAPITAL LETTER A (identifier_start)
  { 0x1057c, 15, 1 }, // VITHKUQI CAPITAL LETTER HA (identifier_start)
  { 0x1058c, 7, 1 }, // VITHKUQI CAPITAL LETTER SE (identifier_start)
  { 0x10594, 2, 1 }, // VITHKUQI CAPITAL LETTER Y (identifier_start)
  { 0x10597, 11, 1 }, // VITHKUQI SMALL LETTER A (identifier_start)
  { 0x105a3, 15, 1 }, // VITHKUQI SMALL LETTER HA (identifier_start)
  { 0x105b3, 7, 1 }, // VITHKUQI SMALL LETTER SE (identifier_start)
  { 0x105bb, 2, 1 }, // VITHKUQI SMALL LETTER Y (identifier_start)
  { 0x10780, 6, 1 }, // MODIFIER LETTER SMALL CAPITAL AA (identifier_start)
  { 0x10787, 42, 1 }, // MODIFIER LETTER SMALL DZ DIGRAPH (identifier_start)
  { 0x107b2, 9, 1 }, // MODIFIER LETTER SMALL CAPITAL Y (identifier_start)
  { 0x10a01, 3, 3 }, // KHAROSHTHI VOWEL SIGN I (identifier_part)
  { 0x10a05, 2, 3 }, // KHAROSHTHI VOWEL SIGN E (identifier_part)
  { 0x10a0c, 4, 3 }, // KHAROSHTHI VOWEL LENGTH MARK (identifier_part)
  { 0x10a38, 3, 3 }, // KHAROSHTHI SIGN BAR ABOVE (identifier_part)
  { 0x10a3f, 1, 3 }, // KHAROSHTHI VIRAMA (identifier_part)
  { 0x10ae5, 2, 3 }, // MANICHAEAN ABBREVIATION MARK ABOVE (identifier_part)
  { 0x10c80, 51, 1 }, // OLD HUNGARIAN CAPITAL LETTER A (identifier_start)
  { 0x10cc0, 51, 1 }, // OLD HUNGARIAN SMALL LETTER A (identifier_start)
  { 0x10d24, 4, 3 }, // HANIFI ROHINGYA SIGN HARBAHAY (identifier_part)
  { 0x10d30, 10, 3 }, // HANIFI ROHINGYA DIGIT ZERO (identifier_part)
  { 0x10eab, 2, 3 }, // YEZIDI COMBINING HAMZA MARK (identifier_part)
  { 0x10efd, 3, 3 }, // ARABIC SMALL LOW WORD SAKTA (identifier_part)
  { 0x10f46, 11, 3 }, // SOGDIAN COMBINING DOT BELOW (identifier_part)
  { 0x10f82, 4, 3 }, // OLD UYGHUR COMBINING DOT ABOVE (identifier_part)
  { 0x11000, 3, 3 }, // BRAHMI SIGN CANDRABINDU (identifier_part)
  { 0x11038, 15, 3 }, // BRAHMI VOWEL SIGN AA (identifier_part)
  { 0x11066, 11, 3 }, // BRAHMI DIGIT ZERO (identifier_part)
  { 0x11073, 2, 3 }, // BRAHMI VOWEL SIGN OLD TAMIL SHORT E (identifier_part)
  { 0x1107f, 4, 3 }, // BRAHMI NUMBER JOINER (identifier_part)
  { 0x110b0, 11, 3 }, // KAITHI VOWEL SIGN AA (identifier_part)
  { 0x110c2, 1, 3 }, // KAITHI VOWEL SIGN VOCALIC R (identifier_part)
  { 0x110f0, 10, 3 }, // SORA SOMPENG DIGIT ZERO (identifier_part)
  { 0x11100, 3, 3 }, // CHAKMA SIGN CANDRABINDU (identifier_part)
  { 0x11127, 14, 3 }, // CHAKMA VOWEL SIGN A (identifier_part)
  { 0x11136, 10, 3 }, // CHAKMA DIGIT ZERO (identifier_part)
  { 0x11145, 2, 3 }, // CHAKMA VOWEL SIGN AA (identifier_part)
  { 0x11173, 1, 3 }, // MAHAJANI SIGN NUKTA (identifier_part)
  { 0x11180, 3, 3 }, // SHARADA SIGN CANDRABINDU (identifier_part)
  { 0x111b3, 14, 3 }, // SHARADA VOWEL SIGN AA (identifier_part)
  { 0x111c9, 4, 3 }, // SHARADA SANDHI MARK (identifier_part)
  { 0x111ce, 12, 3 }, // SHARADA VOWEL SIGN PRISHTHAMATRA E (identifier_part)
  { 0x1122c, 12, 3 }, // KHOJKI VOWEL SIGN AA (identifier_part)
  { 0x1123e, 1, 3 }, // KHOJKI SIGN SUKUN (identifier_part)
  { 0x11241, 1, 3 }, // KHOJKI VOWEL SIGN VOCALIC R (identifier_part)
  { 0x112df, 12, 3 }, // KHUDAWADI SIGN ANUSVARA (identifier_part)
  { 0x112f0, 10, 3 }, // KHUDAWADI DIGIT ZERO (identifier_part)
  { 0x11300, 4, 3 }, // GRANTHA SIGN COMBINING ANUSVARA ABOVE (identifier_part)
  { 0x1133b, 2, 3 }, // COMBINING BINDU BELOW (identifier_part)
  { 0x1133e, 7, 3 }, // GRANTHA VOWEL SIGN AA (identifier_part)
  { 0x11347, 2, 3 }, // GRANTHA VOWEL SIGN EE (identifier_part)
  { 0x1134b, 3, 3 }, // GRANTHA VOWEL SIGN OO (identifier_part)
  { 0x11357, 1, 3 }, // GRANTHA AU LENGTH MARK (identifier_part)
  { 0x11362, 2, 3 }, // GRANTHA VOWEL SIGN VOCALIC L (identifier_part)
  { 0x11366, 7, 3 }, // COMBINING GRANTHA DIGIT ZERO (identifier_part)
  { 0x11370, 5, 3 }, // COMBINING GRANTHA LETTER A (identifier_part)
  { 0x11435, 18, 3 }, // NEWA VOWEL SIGN AA (identifier_part)
  { 0x11450, 10, 3 }, // NEWA DIGIT ZERO (identifier_part)
  { 0x1145e, 1, 3 }, // NEWA SANDHI MARK (identifier_part)
  { 0x114b0, 20, 3 }, // TIRHUTA VOWEL SIGN AA (identifier_part)
  { 0x114d0, 10, 3 }, // TIRHUTA DIGIT ZERO (identifier_part)
  { 0x115af, 7, 3 }, // SIDDHAM VOWEL SIGN AA (identifier_part)
  { 0x115b8, 9, 3 }, // SIDDHAM VOWEL SIGN E (identifier_part)
  { 0x115dc, 2, 3 }, // SIDDHAM VOWEL SIGN ALTERNATE U (identifier_part)
  { 0x11630, 17, 3 }, // MODI VOWEL SIGN AA (identifier_part)
  { 0x11650, 10, 3 }, // MODI DIGIT ZERO (identifier_part)
  { 0x116ab, 13, 3 }, // TAKRI SIGN ANUSVARA (identifier_part)
  { 0x116c0, 10, 3 }, // TAKRI DIGIT ZERO (identifier_part)
  { 0x1171d, 15, 3 }, // AHOM CONSONANT SIGN MEDIAL LA (identifier_part)
  { 0x11730, 10, 3 }, // AHOM DIGIT ZERO (identifier_part)
  { 0x1182c, 15, 3 }, // DOGRA VOWEL SIGN AA (identifier_part)
  { 0x118a0, 64, 1 }, // WARANG CITI CAPITAL LETTER NGAA (identifier_start)
  { 0x118e0, 10, 3 }, // WARANG CITI DIGIT ZERO (identifier_part)
  { 0x11930, 6, 3 }, // DIVES AKURU VOWEL SIGN AA (identifier_part)
  { 0x11937, 2, 3 }, // DIVES AKURU VOWEL SIGN AI (identifier_part)
  { 0x1193b, 4, 3 }, // DIVES AKURU SIGN ANUSVARA (identifier_part)
  { 0x11940, 1, 3 }, // DIVES AKURU MEDIAL YA (identifier_part)
  { 0x11942, 2, 3 }, // DIVES AKURU MEDIAL RA (identifier_part)
  { 0x11950, 10, 3 }, // DIVES AKURU DIGIT ZERO (identifier_part)
  { 0x119d1, 7, 3 }, // NANDINAGARI VOWEL SIGN AA (identifier_part)
  { 0x119da, 7, 3 }, // NANDINAGARI VOWEL SIGN E (identifier_part)
  { 0x119e4, 1, 3 }, // NANDINAGARI VOWEL SIGN PRISHTHAMATRA E (identifier_part)
  { 0x11a01, 10, 3 }, // ZANABAZAR SQUARE VOWEL SIGN I (identifier_part)
  { 0x11a33, 7, 3 }, // ZANABAZAR SQUARE FINAL CONSONANT MARK (identifier_part)
  { 0x11a3b, 4, 3 }, // ZANABAZAR SQUARE CLUSTER-FINAL LETTER YA (identifier_part)
  { 0x11a47, 1, 3 }, // ZANABAZAR SQUARE SUBJOINER (identifier_part)
  { 0x11a51, 11, 3 }, // SOYOMBO VOWEL SIGN I (identifier_part)
  { 0x11a8a, 16, 3 }, // SOYOMBO FINAL CONSONANT SIGN G (identifier_part)
  { 0x11c2f, 8, 3 }, // BHAIKSUKI VOWEL SIGN AA (identifier_part)
  { 0x11c38, 8, 3 }, // BHAIKSUKI VOWEL SIGN E (identifier_part)
  { 0x11c50, 10, 3 }, // BHAIKSUKI DIGIT ZERO (identifier_part)
  { 0x11c92, 22, 3 }, // MARCHEN SUBJOINED LETTER KA (identifier_part)
  { 0x11ca9, 14, 3 }, // MARCHEN SUBJOINED LETTER YA (identifier_part)
  { 0x11d31, 6, 3 }, // MASARAM GONDI VOWEL SIGN AA (identifier_part)
  { 0x11d3a, 1, 3 }, // MASARAM GONDI VOWEL SIGN E (identifier_part)
  { 0x11d3c, 2, 3 }, // MASARAM GONDI VOWEL SIGN AI (identifier_part)
  { 0x11d3f, 7, 3 }, // MASARAM GONDI VOWEL SIGN AU (identifier_part)
  { 0x11d47, 1, 3 }, // MASARAM GONDI RA-KARA (identifier_part)
  { 0x11d50, 10, 3 }, // MASARAM GONDI DIGIT ZERO (identifier_part)
  { 0x11d8a, 5, 3 }, // GUNJALA GONDI VOWEL SIGN AA (identifier_part)
  { 0x11d90, 2, 3 }, // GUNJALA GONDI VOWEL SIGN EE (identifier_part)
  { 0x11d93, 5, 3 }, // GUNJALA GONDI VOWEL SIGN OO (identifier_part)
  { 0x11da0, 10, 3 }, // GUNJALA GONDI DIGIT ZERO (identifier_part)
  { 0x11ef3, 4, 3 }, // MAKASAR VOWEL SIGN I (identifier_part)
  { 0x11f00, 2, 3 }, // KAWI SIGN CANDRABINDU (identifier_part)
  { 0x11f03, 1, 3 }, // KAWI SIGN VISARGA (identifier_part)
  { 0x11f34, 7, 3 }, // KAWI VOWEL SIGN AA (identifier_part)
  { 0x11f3e, 5, 3 }, // KAWI VOWEL SIGN E (identifier_part)
  { 0x11f50, 10, 3 }, // KAWI DIGIT ZERO (identifier_part)
  { 0x12400, 111, 1 }, // CUNEIFORM NUMERIC SIGN TWO ASH (identifier_start)
  { 0x13440, 1, 3 }, // EGYPTIAN HIEROGLYPH MIRROR HORIZONTALLY (identifier_part)
  { 0x13447, 15, 3 }, // EGYPTIAN HIEROGLYPH MODIFIER DAMAGED AT TOP START (identifier_part)
  { 0x16a60, 10, 3 }, // MRO DIGIT ZERO (identifier_part)
  { 0x16ac0, 10, 3 }, // TANGSA DIGIT ZERO (identifier_part)
  { 0x16af0, 5, 3 }, // BASSA VAH COMBINING HIGH TONE (identifier_part)
  { 0x16b30, 7, 3 }, // PAHAWH HMONG MARK CIM TUB (identifier_part)
  { 0x16b40, 4, 1 }, // PAHAWH HMONG SIGN VOS SEEV (identifier_start)
  { 0x16b50, 10, 3 }, // PAHAWH HMONG DIGIT ZERO (identifier_part)
  { 0x16e40, 64, 1 }, // MEDEFAIDRIN CAPITAL LETTER M (identifier_start)
  { 0x16f4f, 1, 3 }, // MIAO SIGN CONSONANT MODIFIER BAR (identifier_part)
  { 0x16f51, 55, 3 }, // MIAO SIGN ASPIRATION (identifier_part)
  { 0x16f8f, 4, 3 }, // MIAO TONE RIGHT (identifier_part)
  { 0x16f93, 13, 1 }, // MIAO LETTER TONE-2 (identifier_start)
  { 0x16fe0, 2, 1 }, // TANGUT ITERATION MARK (identifier_start)
  { 0x16fe3, 1, 1 }, // OLD CHINESE ITERATION MARK (identifier_start)
  { 0x16fe4, 1, 3 }, // KHITAN SMALL SCRIPT FILLER (identifier_part)
  { 0x16ff0, 2, 3 }, // VIETNAMESE ALTERNATE READING MARK CA (identifier_part)
  { 0x1aff0, 4, 1 }, // KATAKANA LETTER MINNAN TONE-2 (identifier_start)
  { 0x1aff5, 7, 1 }, // KATAKANA LETTER MINNAN TONE-7 (identifier_start)
  { 0x1affd, 2, 1 }, // KATAKANA LETTER MINNAN NASALIZED TONE-7 (identifier_start)
  { 0x1bc9d, 2, 3 }, // DUPLOYAN THICK LETTER SELECTOR (identifier_part)
  { 0x1cf00, 46, 3 }, // ZNAMENNY COMBINING MARK GORAZDO NIZKO S KRYZHEM ON LEFT (identifier_part)
  { 0x1cf30, 23, 3 }, // ZNAMENNY COMBINING TONAL RANGE MARK MRACHNO (identifier_part)
  { 0x1d165, 5, 3 }, // MUSICAL SYMBOL COMBINING STEM (identifier_part)
  { 0x1d16d, 6, 3 }, // MUSICAL SYMBOL COMBINING AUGMENTATION DOT (identifier_part)
  { 0x1d17b, 8, 3 }, // MUSICAL SYMBOL COMBINING ACCENT (identifier_part)
  { 0x1d185, 7, 3 }, // MUSICAL SYMBOL COMBINING DOIT (identifier_part)
  { 0x1d1aa, 4, 3 }, // MUSICAL SYMBOL COMBINING DOWN BOW (identifier_part)
  { 0x1d242, 3, 3 }, // COMBINING GREEK MUSICAL TRISEME (identifier_part)
  { 0x1d400, 85, 1 }, // MATHEMATICAL BOLD CAPITAL A (identifier_start)
  { 0x1d456, 71, 1 }, // MATHEMATICAL ITALIC SMALL I (identifier_start)
  { 0x1d49e, 2, 1 }, // MATHEMATICAL SCRIPT CAPITAL C (identifier_start)
  { 0x1d4a2, 1, 1 }, // MATHEMATICAL SCRIPT CAPITAL G (identifier_start)
  { 0x1d4a5, 2, 1 }, // MATHEMATICAL SCRIPT CAPITAL J (identifier_start)
  { 0x1d4a9, 4, 1 }, // MATHEMATICAL SCRIPT CAPITAL N (identifier_start)
  { 0x1d4ae, 12, 1 }, // MATHEMATICAL SCRIPT CAPITAL S (identifier_start)
  { 0x1d4bb, 1, 1 }, // MATHEMATICAL SCRIPT SMALL F (identifier_start)
  { 0x1d4bd, 7, 1 }, // MATHEMATICAL SCRIPT SMALL H (identifier_start)
  { 0x1d4c5, 65, 1 }, // MATHEMATICAL SCRIPT SMALL P (identifier_start)
  { 0x1d507, 4, 1 }, // MATHEMATICAL FRAKTUR CAPITAL D (identifier_start)
  { 0x1d50d, 8, 1 }, // MATHEMATICAL FRAKTUR CAPITAL J (identifier_start)
  { 0x1d516, 7, 1 }, // MATHEMATICAL FRAKTUR CAPITAL S (identifier_start)
  { 0x1d51e, 28, 1 }, // MATHEMATICAL FRAKTUR SMALL A (identifier_start)
  { 0x1d53b, 4, 1 }, // MATHEMATICAL DOUBLE-STRUCK CAPITAL D (identifier_start)
  { 0x1d540, 5, 1 }, // MATHEMATICAL DOUBLE-STRUCK CAPITAL I (identifier_start)
  { 0x1d546, 1, 1 }, // MATHEMATICAL DOUBLE-STRUCK CAPITAL O (identifier_start)
  { 0x1d54a, 7, 1 }, // MATHEMATICAL DOUBLE-STRUCK CAPITAL S (identifier_start)
  { 0x1d552, 340, 1 }, // MATHEMATICAL DOUBLE-STRUCK SMALL A (identifier_start)
  { 0x1d6a8, 25, 1 }, // MATHEMATICAL BOLD CAPITAL ALPHA (identifier_start)
  { 0x1d6c2, 25, 1 }, // MATHEMATICAL BOLD SMALL ALPHA (identifier_start)
  { 0x1d6dc, 31, 1 }, // MATHEMATICAL BOLD EPSILON SYMBOL (identifier_start)
  { 0x1d6fc, 25, 1 }, // MATHEMATICAL ITALIC SMALL ALPHA (identifier_start)
  { 0x1d716, 31, 1 }, // MATHEMATICAL ITALIC EPSILON SYMBOL (identifier_start)
  { 0x1d736, 25, 1 }, // MATHEMATICAL BOLD ITALIC SMALL ALPHA (identifier_start)
  { 0x1d750, 31, 1 }, // MATHEMATICAL BOLD ITALIC EPSILON SYMBOL (identifier_start)
  { 0x1d770, 25, 1 }, // MATHEMATICAL SANS-SERIF BOLD SMALL ALPHA (identifier_start)
  { 0x1d78a, 31, 1 }, // MATHEMATICAL SANS-SERIF BOLD EPSILON SYMBOL (identifier_start)
  { 0x1d7aa, 25, 1 }, // MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ALPHA (identifier_start)
  { 0x1d7c4, 8, 1 }, // MATHEMATICAL SANS-SERIF BOLD ITALIC EPSILON SYMBOL (identifier_start)
  { 0x1d7ce, 50, 3 }, // MATHEMATICAL BOLD DIGIT ZERO (identifier_part)
  { 0x1da00, 55, 3 }, // SIGNWRITING HEAD RIM (identifier_part)
  { 0x1da3b, 50, 3 }, // SIGNWRITING MOUTH CLOSED NEUTRAL (identifier_part)
  { 0x1da75, 1, 3 }, // SIGNWRITING UPPER BODY TILTING FROM HIP JOINTS (identifier_part)
  { 0x1da84, 1, 3 }, // SIGNWRITING LOCATION HEAD NECK (identifier_part)
  { 0x1da9b, 5, 3 }, // SIGNWRITING FILL MODIFIER-2 (identifier_part)
  { 0x1daa1, 15, 3 }, // SIGNWRITING ROTATION MODIFIER-2 (identifier_part)
  { 0x1df00, 10, 1 }, // LATIN SMALL LETTER FENG DIGRAPH WITH TRILL (identifier_start)
  { 0x1df0b, 20, 1 }, // LATIN SMALL LETTER ESH WITH DOUBLE BAR (identifier_start)
  { 0x1df25, 6, 1 }, // LATIN SMALL LETTER D WITH MID-HEIGHT LEFT HOOK (identifier_start)
  { 0x1e000, 7, 3 }, // COMBINING GLAGOLITIC LETTER AZU (identifier_part)
  { 0x1e008, 17, 3 }, // COMBINING GLAGOLITIC LETTER ZEMLJA (identifier_part)
  { 0x1e01b, 7, 3 }, // COMBINING GLAGOLITIC LETTER SHTA (identifier_part)
  { 0x1e023, 2, 3 }, // COMBINING GLAGOLITIC LETTER YU (identifier_part)
  { 0x1e026, 5, 3 }, // COMBINING GLAGOLITIC LETTER YO (identifier_part)
  { 0x1e030, 62, 1 }, // MODIFIER LETTER CYRILLIC SMALL A (identifier_start)
  { 0x1e08f, 1, 3 }, // COMBINING CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I (identifier_part)
  { 0x1e130, 7, 3 }, // NYIAKENG PUACHUE HMONG TONE-B (identifier_part)
  { 0x1e137, 7, 1 }, // NYIAKENG PUACHUE HMONG SIGN FOR PERSON (identifier_start)
  { 0x1e140, 10, 3 }, // NYIAKENG PUACHUE HMONG DIGIT ZERO (identifier_part)
  { 0x1e2ae, 1, 3 }, // TOTO SIGN RISING TONE (identifier_part)
  { 0x1e2ec, 14, 3 }, // WANCHO TONE TUP (identifier_part)
  { 0x1e4eb, 1, 1 }, // NAG MUNDARI SIGN OJOD (identifier_start)
  { 0x1e4ec, 14, 3 }, // NAG MUNDARI SIGN MUHOR (identifier_part)
  { 0x1e8d0, 7, 3 }, // MENDE KIKAKUI COMBINING NUMBER TEENS (identifier_part)
  { 0x1e900, 68, 1 }, // ADLAM CAPITAL LETTER ALIF (identifier_start)
  { 0x1e944, 7, 3 }, // ADLAM ALIF LENGTHENER (identifier_part)
  { 0x1e94b, 1, 1 }, // ADLAM NASALIZATION MARK (identifier_start)
  { 0x1e950, 10, 3 }, // ADLAM DIGIT ZERO (identifier_part)
  { 0x1fbf0, 10, 3 }, // SEGMENTED DIGIT ZERO (identifier_part)
  { 0xe0100, 240, 3 }, // VARIATION SELECTOR-17 (identifier_part)
}};

} // end namespace peejay
#endif // PEEJAY_CPRUN_HPP
